# Generated by Django 5.1 on 2024-11-27 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes_shop', '0010_remove_shipping_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
