# Generated by Django 5.1 on 2024-12-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes_shop', '0011_remove_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stripe_checkout_session_id',
            field=models.CharField(default=None, max_length=255, null=True, unique=True),
        ),
    ]
